import Head from 'next/head'
import Aspanion from '../components/Aspanion'
import LaunchCountdown from '../components/LaunchCountDown'
import Gallery from '../components/Gallery'
import handler from '../pages/api/desaster/2022'
import fs from 'node:fs/promises'
import path from 'node:path'


export default function Home({ images }) {
  return (
    <>
      <Head>
        <title>Desaster Fest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='bg-gradient-to-r from-cyan-500 to-blue-300 p-4 flex flex-col justify-around header'>
        <h1 className="text-amber-50 text-5xl font-bold leading-tight">
          Bienvenido a
          <br />
          Desaster Fest
          <p className='text-amber-50 text-2xl text-right italic'>Edición 2023</p>
        </h1>


        <LaunchCountdown date={"09/09/2023 16:00:00"} />
        <button className='bg-red-300 rounded-md p-3 mt-2 w-80 md:w-96 font-bold text-white self-center'>Comprar entradas</button>
      </header>

      <main className='p-4'>
        <Aspanion />
        <section>
          <h2 className='text-3xl text-center font-bold'>Desaster Fest 2022</h2>
          <p className='py-2'>Por si alguien estuvo en Narnia el año pasado y se perdió lo que fue la primera edición de este
            gran evento, aquí les dejamos un resumen de lo que fue esta experiencia.
          </p>
          <Gallery images={images} />
        </section>
      </main>

      
    </>
  )
}

export async function getStaticProps(context) {
  const jsonDirectory = path.join(process.cwd(), '/public/disaster2022')
  const images = await fs.readdir(jsonDirectory, 'utf8')
  return {
    props: {
      images
    }
  }
}
