import Head from 'next/head'
import Aspanion from '../components/Aspanion'
import LaunchCountdown from '../components/LaunchCountDown'

export default function Home() {
  return (
    <>
      <Head>
        <title>Desaster Fest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='h-14 bg-gradient-to-r from-cyan-500 to-blue-300 p-4 flex flex-col'>
        <h1 className="text-amber-50 text-5xl font-bold leading-tight">
          Bienvenido a
          <br></br>
          Desaster Fest
        </h1>
        <p className='text-amber-50 text-2xl text-right italic'>Edición 2023</p>
       
        <LaunchCountdown date={ "01/30/2023 00:00:00"}/>
        <button className='bg-red-300 rounded-md p-3 mt-2 md:w-52'>Comprar entradas</button>
      </header>
      <Aspanion />
    </>
  )
}
