import Head from 'next/head'
import Aspanion from '../components/Aspanion'
import Gallery from '../components/Gallery'
import dynamic from 'next/dynamic'

import fs from 'node:fs/promises'
import path from 'node:path'
import Background from '../components/Background'
import Script from 'next/script'

export default function Home({ images }) {
  const DynamicComponent = dynamic(() =>
    import('../components/Countdown'), { ssr: false }
  )

  return (
    <>
      <Script src="/background.js" />
      <Script src="/navigation.js" />
      <Head>
        <title>Desaster Fest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Background />

      <header id='top' className='min-h-screen'>
        <h1 className='text-primary text-xl xl:text-[54px] leading-none text-center font-black uppercase italic -rotate-[10deg]'>
          <span className='text-6xl lg:text-8xl xl:text-9xl block'>Evento</span>
          <span className='max-w-[38rem] m-auto'>
            de música electrónica
          </span>
          <span className='max-w-[38rem] m-auto block'>
            II Edición
          </span>
        </h1>

        <div className='text-center mt-10 flex justify-center flex-col'>
          <h2 className='animate-fadeIn animate-delay-200 italic font-extrabold text-5xl lg:text-6xl text-white -rotate-[10deg]'>9 de septiembre</h2>
          <h3 className='animate-fadeIn animate-delay-200 italic text-white/80 text-lg -rotate-[10deg]'>A partir de las 16:00 horas
          <span className='px-2'>·</span> Recinto ferial Almenara
          </h3>

          <div className='m-auto mt-8 animate-fadeIn animate-delay-500'>
            <DynamicComponent />
          </div>
        </div>
      </header>

      <main className='p-4'>
        <Aspanion />
        <section>
          <h2 className='text-3xl text-center font-bold'>Desaster Fest 2022</h2>
          <p className='py-2'>Por si alguien estuvo en Narnia el año pasado y se perdió lo que fue la primera edición de este
            gran evento, aquí les dejamos un resumen de lo que fue esta experiencia.
          </p>
          <Gallery images={images} />
        </section>
      </main>


    </>
  )
}

export async function getStaticProps(context) {
  const jsonDirectory = path.join(process.cwd(), '/public/disaster2022')
  const images = await fs.readdir(jsonDirectory, 'utf8')
  return {
    props: {
      images
    }
  }
}
